### PR TITLE
✨ Support JupyterLab 4 🍻

### PR DESCRIPTION
**Pull request by mengyanw**

### CODE REVIEW

**Comment by s-weigand** [comment]
@mengyanw Thanks a lot for this PR ❤

**Comment by s-weigand** [comment]
all-contributors please add @mengyanw for code

**Comment by s-weigand** [comment]
@all-contributors please add @mengyanw for code

**Comment by s-weigand** [comment]
@all-contributors please add @mengyanw for maintenance

**Comment by s-weigand** [comment]
@mengyanw I [just released version `0.4.0`](https://pypi.org/project/jupyterlab-autosave-on-focus-change/) (thought it is more fitting than `0.3.0` due to the nature of the change 😅)
Had to do quite some extra infra changes to get everything working again, as was to be expected to be after nearly 2y 😅

**Comment by mengyanw** [comment]
@s-weigand Hahaha true. I am so excited to install the new version!

**Pull request merged**
